name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Install node modules
        run: npm install
    
      - name: Activate Syncfusion License
        run: npx syncfusion-license activate
        env:
          SYNCFUSION_LICENSE: $
