name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14
        
      - name: Install node modules
          cd  /home/runner/work/SansTech1121.github.io/
        run: npm install

      - name: Build and Test
        run: npm run build
        
      - name: Activate Syncfusion License
        run: npx syncfusion-license activate
        env:
          SYNCFUSION_LICENSE: $
